- name: Verify Ansible meets version requirements.
  assert:
    that: ansible_version.full is version('2.9.5', '>=') 
    msg: >
      "You must update Ansible to at least 2.9.5 to use this playbook."